config/routes.rb
DiagnoseMe::Application.routes.draw do
  resources :diagnoses

  resources :diagnosis_requests

  resources :doctors

  resources :patients

end

app/controllers/diagnoses_controller.rb
class DiagnosesController < ApplicationController
  # GET /diagnoses
  # GET /diagnoses.json
  def index
    @diagnoses = Diagnosis.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @diagnoses }
    end
  end

  # GET /diagnoses/1
  # GET /diagnoses/1.json
  def show
    @diagnosis = Diagnosis.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @diagnosis }
    end
  end

  # GET /diagnoses/new
  # GET /diagnoses/new.json
  def new
    @diagnosis = Diagnosis.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @diagnosis }
    end
  end

  # GET /diagnoses/1/edit
  def edit
    @diagnosis = Diagnosis.find(params[:id])
  end

  # POST /diagnoses
  # POST /diagnoses.json
  def create
    @diagnosis = Diagnosis.new(params[:diagnosis])

    respond_to do |format|
      if @diagnosis.save
        format.html { redirect_to @diagnosis, notice: 'Diagnosis was successfully created.' }
        format.json { render json: @diagnosis, status: :created, location: @diagnosis }
      else
        format.html { render action: "new" }
        format.json { render json: @diagnosis.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /diagnoses/1
  # PUT /diagnoses/1.json
  def update
    @diagnosis = Diagnosis.find(params[:id])

    respond_to do |format|
      if @diagnosis.update_attributes(params[:diagnosis])
        format.html { redirect_to @diagnosis, notice: 'Diagnosis was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @diagnosis.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diagnoses/1
  # DELETE /diagnoses/1.json
  def destroy
    @diagnosis = Diagnosis.find(params[:id])
    @diagnosis.destroy

    respond_to do |format|
      format.html { redirect_to diagnoses_url }
      format.json { head :ok }
    end
  end
end

app/helpers/diagnoses_helper.rb
module DiagnosesHelper
end

app/views/diagnoses/_form.html.erb
<%= form_for(@diagnosis) do |f| %>
  <% if @diagnosis.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@diagnosis.errors.count, "error") %> prohibited this diagnosis from being saved:</h2>

      <ul>
      <% @diagnosis.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/diagnoses/edit.html.erb
<h1>Editing diagnosis</h1>

<%= render 'form' %>

<%= link_to 'Show', @diagnosis %> |
<%= link_to 'Back', diagnoses_path %>

app/views/diagnoses/index.html.erb
<h1>Listing diagnoses</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @diagnoses.each do |diagnosis| %>
  <tr>
    <td><%= link_to 'Show', diagnosis %></td>
    <td><%= link_to 'Edit', edit_diagnosis_path(diagnosis) %></td>
    <td><%= link_to 'Destroy', diagnosis, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Diagnosis', new_diagnosis_path %>

app/views/diagnoses/new.html.erb
<h1>New diagnosis</h1>

<%= render 'form' %>

<%= link_to 'Back', diagnoses_path %>

app/views/diagnoses/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_diagnosis_path(@diagnosis) %> |
<%= link_to 'Back', diagnoses_path %>