config/routes.rb
DiagnoseMe::Application.routes.draw do
  resources :diagnoses

  resources :diagnosis_requests

  resources :doctors

  resources :patients

end

app/models/diagnosis_request.rb
class DiagnosisRequest < ActiveRecord::Base
end

app/controllers/diagnosis_requests_controller.rb
class DiagnosisRequestsController < ApplicationController
  # GET /diagnosis_requests
  # GET /diagnosis_requests.json
  def index
    @diagnosis_requests = DiagnosisRequest.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @diagnosis_requests }
    end
  end

  # GET /diagnosis_requests/1
  # GET /diagnosis_requests/1.json
  def show
    @diagnosis_request = DiagnosisRequest.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @diagnosis_request }
    end
  end

  # GET /diagnosis_requests/new
  # GET /diagnosis_requests/new.json
  def new
    @diagnosis_request = DiagnosisRequest.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @diagnosis_request }
    end
  end

  # GET /diagnosis_requests/1/edit
  def edit
    @diagnosis_request = DiagnosisRequest.find(params[:id])
  end

  # POST /diagnosis_requests
  # POST /diagnosis_requests.json
  def create
    @diagnosis_request = DiagnosisRequest.new(params[:diagnosis_request])

    respond_to do |format|
      if @diagnosis_request.save
        format.html { redirect_to @diagnosis_request, notice: 'Diagnosis request was successfully created.' }
        format.json { render json: @diagnosis_request, status: :created, location: @diagnosis_request }
      else
        format.html { render action: "new" }
        format.json { render json: @diagnosis_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /diagnosis_requests/1
  # PUT /diagnosis_requests/1.json
  def update
    @diagnosis_request = DiagnosisRequest.find(params[:id])

    respond_to do |format|
      if @diagnosis_request.update_attributes(params[:diagnosis_request])
        format.html { redirect_to @diagnosis_request, notice: 'Diagnosis request was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @diagnosis_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diagnosis_requests/1
  # DELETE /diagnosis_requests/1.json
  def destroy
    @diagnosis_request = DiagnosisRequest.find(params[:id])
    @diagnosis_request.destroy

    respond_to do |format|
      format.html { redirect_to diagnosis_requests_url }
      format.json { head :ok }
    end
  end
end

app/helpers/diagnosis_requests_helper.rb
module DiagnosisRequestsHelper
end

app/views/diagnosis_requests/_form.html.erb
<%= form_for(@diagnosis_request) do |f| %>
  <% if @diagnosis_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@diagnosis_request.errors.count, "error") %> prohibited this diagnosis_request from being saved:</h2>

      <ul>
      <% @diagnosis_request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/diagnosis_requests/edit.html.erb
<h1>Editing diagnosis_request</h1>

<%= render 'form' %>

<%= link_to 'Show', @diagnosis_request %> |
<%= link_to 'Back', diagnosis_requests_path %>

app/views/diagnosis_requests/index.html.erb
<h1>Listing diagnosis_requests</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @diagnosis_requests.each do |diagnosis_request| %>
  <tr>
    <td><%= link_to 'Show', diagnosis_request %></td>
    <td><%= link_to 'Edit', edit_diagnosis_request_path(diagnosis_request) %></td>
    <td><%= link_to 'Destroy', diagnosis_request, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Diagnosis request', new_diagnosis_request_path %>

app/views/diagnosis_requests/new.html.erb
<h1>New diagnosis_request</h1>

<%= render 'form' %>

<%= link_to 'Back', diagnosis_requests_path %>

app/views/diagnosis_requests/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_diagnosis_request_path(@diagnosis_request) %> |
<%= link_to 'Back', diagnosis_requests_path %>